# revision 34302
# category Collection
# catalog-ctan undef
# catalog-date undef
# catalog-license undef
# catalog-version undef
Name:		texlive-collection-latexextra
Epoch:		1
Version:	20190406
Release:	1
Summary:	LaTeX additional packages
Group:		Publishing
URL:		http://tug.org/texlive
License:	http://www.tug.org/texlive/LICENSE.TL
Source0:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/collection-latexextra.tar.xz
BuildArch:	noarch
BuildRequires:	texlive-tlpkg
Requires(pre):	texlive-tlpkg
Suggests:	texlive-exceltex
Requires:	texlive-collection-latexrecommended
Requires:	texlive-collection-pictures
Requires:	texlive-2up
Requires:	texlive-ESIEEcv
Requires:	texlive-GS1
Requires:	texlive-HA-prosper
Requires:	texlive-Tabbing
Requires:	texlive-a0poster
Requires:	texlive-a4wide
Requires:	texlive-a5comb
Requires:	texlive-abraces
Requires:	texlive-abstract
Requires:	texlive-achemso
Requires:	texlive-acro
Requires:	texlive-acronym
Requires:	texlive-acroterm
Requires:	texlive-actuarialangle
Requires:	texlive-addlines
Requires:	texlive-adjmulticol
Requires:	texlive-adjustbox
Requires:	texlive-adrconv
Requires:	texlive-advdate
Requires:	texlive-akktex
Requires:	texlive-akletter
Requires:	texlive-alterqcm
Requires:	texlive-altfont
Requires:	texlive-amsaddr
Requires:	texlive-animate
Requires:	texlive-anonchap
Requires:	texlive-answers
Requires:	texlive-anyfontsize
Requires:	texlive-appendix
Requires:	texlive-appendixnumberbeamer
Requires:	texlive-apptools
Requires:	texlive-arcs
Requires:	texlive-arrayjobx
Requires:	texlive-arraysort
Requires:	texlive-assignment
Requires:	texlive-attachfile
Requires:	texlive-autopdf
Requires:	texlive-authoraftertitle
Requires:	texlive-authorindex
Requires:	texlive-autonum
Requires:	texlive-background
Requires:	texlive-bashful
Requires:	texlive-bchart
Requires:	texlive-beamer2thesis
Requires:	texlive-beameraudience
Requires:	texlive-beamerposter
Requires:	texlive-beamersubframe
Requires:	texlive-beamertheme-upenn-bc
Requires:	texlive-beamerthemejltree
Requires:	texlive-beamerthemenirma
Requires:	texlive-beamerthemephnompenh
Requires:	texlive-beton
Requires:	texlive-bez123
Requires:	texlive-bezos
Requires:	texlive-bhcexam
Requires:	texlive-bigfoot
Requires:	texlive-bigints
Requires:	texlive-bizcard
Requires:	texlive-blindtext
Requires:	texlive-blkarray
Requires:	texlive-block
Requires:	texlive-blowup
Requires:	texlive-boites
Requires:	texlive-bold-extra
Requires:	texlive-bookest
Requires:	texlive-booklet
Requires:	texlive-boolexpr
Requires:	texlive-bophook
Requires:	texlive-boxedminipage
Requires:	texlive-boxhandler
Requires:	texlive-bracketkey
Requires:	texlive-braket
Requires:	texlive-breakurl
Requires:	texlive-bullcntr
Requires:	texlive-bussproofs
Requires:	texlive-bxdpx-beamer
Requires:	texlive-calcage
Requires:	texlive-calctab
Requires:	texlive-calculator
Requires:	texlive-calrsfs
Requires:	texlive-cals
Requires:	texlive-calxxxx-yyyy
Requires:	texlive-cancel
Requires:	texlive-canoniclayout
Requires:	texlive-capt-of
Requires:	texlive-captcont
Requires:	texlive-captdef
Requires:	texlive-cases
Requires:	texlive-casyl
Requires:	texlive-catchfilebetweentags
Requires:	texlive-catechis
Requires:	texlive-catoptions
Requires:	texlive-cbcoptic
Requires:	texlive-ccaption
Requires:	texlive-cclicenses
Requires:	texlive-cd
Requires:	texlive-cd-cover
Requires:	texlive-cdpbundl
Requires:	texlive-cellspace
Requires:	texlive-censor
Requires:	texlive-changebar
Requires:	texlive-changelayout
Requires:	texlive-changepage
Requires:	texlive-changes
Requires:	texlive-chappg
Requires:	texlive-chapterfolder
Requires:	texlive-chet
Requires:	texlive-chextras
Requires:	texlive-chkfloat
Requires:	texlive-chletter
Requires:	texlive-chngcntr
Requires:	texlive-chronology
Requires:	texlive-circ
Requires:	texlive-classics
Requires:	texlive-clefval
Requires:	texlive-cleveref
Requires:	texlive-clipboard
Requires:	texlive-clock
Requires:	texlive-cmdstring
Requires:	texlive-cmdtrack
Requires:	texlive-cmsd
Requires:	texlive-cnltx
Requires:	texlive-codedoc
Requires:	texlive-codepage
Requires:	texlive-collcell
Requires:	texlive-collectbox
Requires:	texlive-colordoc
Requires:	texlive-colorinfo
Requires:	texlive-colortab
Requires:	texlive-colorwav
Requires:	texlive-colorweb
Requires:	texlive-colourchange
Requires:	texlive-combelow
Requires:	texlive-combine
Requires:	texlive-comma
Requires:	texlive-commado
Requires:	texlive-comment
Requires:	texlive-concepts
Requires:	texlive-concprog
Requires:	texlive-constants
Requires:	texlive-contour
Requires:	texlive-contracard
Requires:	texlive-cooking
Requires:	texlive-cool
Requires:	texlive-coollist
Requires:	texlive-coolstr
Requires:	texlive-coolthms
Requires:	texlive-cooltooltips
Requires:	texlive-coordsys
Requires:	texlive-copyrightbox
Requires:	texlive-coseoul
Requires:	texlive-counttexruns
Requires:	texlive-courseoutline
Requires:	texlive-coursepaper
Requires:	texlive-coverpage
Requires:	texlive-cprotect
Requires:	texlive-crbox
Requires:	texlive-crossreference
Requires:	texlive-csquotes
Requires:	texlive-csvsimple
Requires:	texlive-csvtools
Requires:	texlive-cuisine
Requires:	texlive-currfile
Requires:	texlive-currvita
Requires:	texlive-cutwin
Requires:	texlive-cv
Requires:	texlive-cv4tw
Requires:	texlive-cweb-latex
Requires:	texlive-dashbox
Requires:	texlive-dashrule
Requires:	texlive-dashundergaps
Requires:	texlive-dataref
Requires:	texlive-datatool
Requires:	texlive-dateiliste
Requires:	texlive-datenumber
Requires:	texlive-datetime
Requires:	texlive-dblfloatfix
Requires:	texlive-decimal
Requires:	texlive-decorule
Requires:	texlive-delim
Requires:	texlive-delimtxt
Requires:	texlive-detlev-cm
Requires:	texlive-diagbox
Requires:	texlive-diagnose
Requires:	texlive-dialogl
Requires:	texlive-dichokey
Requires:	texlive-dinbrief
Requires:	texlive-directory
Requires:	texlive-dirtytalk
Requires:	texlive-dlfltxb
Requires:	texlive-dnaseq
Requires:	texlive-docmfp
Requires:	texlive-docmute
Requires:	texlive-documentation
Requires:	texlive-doi
Requires:	texlive-dotarrow
Requires:	texlive-dotseqn
Requires:	texlive-download
Requires:	texlive-dox
Requires:	texlive-dpfloat
Requires:	texlive-dprogress
Requires:	texlive-drac
Requires:	texlive-draftcopy
Requires:	texlive-draftwatermark
Requires:	texlive-dtk
Requires:	texlive-dtxgallery
Requires:	texlive-dvdcoll
Requires:	texlive-dynblocks
Requires:	texlive-easy
Requires:	texlive-easy-todo
Requires:	texlive-easyfig
Requires:	texlive-easylist
Requires:	texlive-ean13isbn
Requires:	texlive-ebezier
Requires:	texlive-ecclesiastic
Requires:	texlive-ecv
Requires:	texlive-ed
Requires:	texlive-edmargin
Requires:	texlive-eemeir
Requires:	texlive-efbox
Requires:	texlive-egplot
Requires:	texlive-ellipsis
Requires:	texlive-elmath
Requires:	texlive-elpres
Requires:	texlive-emarks
Requires:	texlive-embedall
Requires:	texlive-embrac
Requires:	texlive-emptypage
Requires:	texlive-emulateapj
Requires:	texlive-endfloat
Requires:	texlive-endheads
Requires:	texlive-endnotes
Requires:	texlive-engpron
Requires:	texlive-engrec
Requires:	texlive-enotez
Requires:	texlive-enumitem
Requires:	texlive-enumitem-zref
Requires:	texlive-envbig
Requires:	texlive-environ
Requires:	texlive-envlab
Requires:	texlive-epigraph
Requires:	texlive-epiolmec
Requires:	texlive-eqell
Requires:	texlive-eqlist
Requires:	texlive-eqname
Requires:	texlive-eqparbox
Requires:	texlive-errata
Requires:	texlive-esami
Requires:	texlive-esdiff
Requires:	texlive-esint
Requires:	texlive-esint-type1
Requires:	texlive-etaremune
Requires:	texlive-etextools
Requires:	texlive-etoc
Requires:	texlive-etoolbox
Requires:	texlive-eukdate
Requires:	texlive-europecv
Requires:	texlive-everyhook
Requires:	texlive-everypage
Requires:	texlive-exam
Requires:	texlive-exam-n
Requires:	texlive-examdesign
Requires:	texlive-example
Requires:	texlive-examplep
Requires:	texlive-excludeonly
Requires:	texlive-exercise
Requires:	texlive-exp-testopt
Requires:	texlive-expdlist
Requires:	texlive-export
Requires:	texlive-exsheets
Requires:	texlive-exsol
Requires:	texlive-extract
Requires:	texlive-facsimile
Requires:	texlive-factura
Requires:	texlive-fancynum
Requires:	texlive-fancypar
Requires:	texlive-fancytabs
Requires:	texlive-fancytooltips
Requires:	texlive-fifo-stack
Requires:	texlive-figsize
Requires:	texlive-filecontents
Requires:	texlive-filedate
Requires:	texlive-filehook
Requires:	texlive-fileinfo
Requires:	texlive-filemod
Requires:	texlive-fink
Requires:	texlive-finstrut
Requires:	texlive-fixfoot
Requires:	texlive-fixme
Requires:	texlive-fixmetodonotes
Requires:	texlive-fjodor
Requires:	texlive-flabels
Requires:	texlive-flacards
Requires:	texlive-flagderiv
Requires:	texlive-flashcards
Requires:	texlive-flashmovie
Requires:	texlive-flipbook
Requires:	texlive-flippdf
Requires:	texlive-floatflt
Requires:	texlive-floatrow
Requires:	texlive-flowfram
Requires:	texlive-fmp
Requires:	texlive-fmtcount
Requires:	texlive-fn2end
Requires:	texlive-fnbreak
Requires:	texlive-fncychap
Requires:	texlive-fncylab
Requires:	texlive-fnpara
Requires:	texlive-fnpct
Requires:	texlive-fnumprint
Requires:	texlive-foilhtml
Requires:	texlive-fontaxes
Requires:	texlive-fonttable
Requires:	texlive-footmisc
Requires:	texlive-footnotebackref
Requires:	texlive-footnoterange
Requires:	texlive-footnpag
Requires:	texlive-forarray
Requires:	texlive-foreign
Requires:	texlive-forloop
Requires:	texlive-formlett
Requires:	texlive-formular
Requires:	texlive-fragments
Requires:	texlive-frame
Requires:	texlive-framed
Requires:	texlive-frankenstein
Requires:	texlive-frege
Requires:	texlive-ftcap
Requires:	texlive-ftnxtra
Requires:	texlive-fullblck
Requires:	texlive-fullwidth
Requires:	texlive-fundus-calligra
Requires:	texlive-fundus-cyr
Requires:	texlive-fundus-sueterlin
Requires:	texlive-fwlw
Requires:	texlive-g-brief
Requires:	texlive-gauss
Requires:	texlive-gcard
Requires:	texlive-gcite
Requires:	texlive-genmpage
Requires:	texlive-getfiledate
Requires:	texlive-ginpenc
Requires:	texlive-gitinfo
Requires:	texlive-gloss
Requires:	texlive-glossaries
Requires:	texlive-gmdoc
Requires:	texlive-gmdoc-enhance
Requires:	texlive-gmiflink
Requires:	texlive-gmutils
Requires:	texlive-gmverb
Requires:	texlive-graphicx-psmin
Requires:	texlive-graphicxbox
Requires:	texlive-grfpaste
Requires:	texlive-grid
Requires:	texlive-grid-system
Requires:	texlive-gridset
Requires:	texlive-gtl
Requires:	texlive-guitlogo
Requires:	texlive-handout
Requires:	texlive-hanging
Requires:	texlive-hardwrap
Requires:	texlive-harnon-cv
Requires:	texlive-harpoon
Requires:	texlive-hc
Requires:	texlive-he-she
Requires:	texlive-hhtensor
Requires:	texlive-histogr
Requires:	texlive-hitec
Requires:	texlive-hletter
Requires:	texlive-hpsdiss
Requires:	texlive-hrefhide
Requires:	texlive-hvindex
Requires:	texlive-hypdvips
Requires:	texlive-hyper
Requires:	texlive-hypernat
Requires:	texlive-hyperref-docsrc
Requires:	texlive-hyperxmp
Requires:	texlive-hyphenat
Requires:	texlive-idxcmds
Requires:	texlive-idxlayout
Requires:	texlive-ifmslide
Requires:	texlive-ifmtarg
Requires:	texlive-ifnextok
Requires:	texlive-ifoddpage
Requires:	texlive-ifplatform
Requires:	texlive-ifthenx
Requires:	texlive-iitem
Requires:	texlive-image-gallery
Requires:	texlive-imakeidx
Requires:	texlive-import
Requires:	texlive-incgraph
Requires:	texlive-inlinedef
Requires:	texlive-inputtrc
Requires:	texlive-interactiveworkbook
Requires:	texlive-interfaces
Requires:	texlive-inversepath
Requires:	texlive-invoice
Requires:	texlive-iso
Requires:	texlive-iso10303
Requires:	texlive-isodate
Requires:	texlive-isonums
Requires:	texlive-isodoc
Requires:	texlive-isorot
Requires:	texlive-isotope
Requires:	texlive-issuulinks
Requires:	texlive-iwhdp
Requires:	texlive-jlabels
Requires:	texlive-jvlisting
Requires:	texlive-kantlipsum
Requires:	texlive-kerntest
Requires:	texlive-keycommand
Requires:	texlive-keyreader
Requires:	texlive-keystroke
Requires:	texlive-keyval2e
Requires:	texlive-kix
Requires:	texlive-koma-moderncvclassic
Requires:	texlive-koma-script-sfs
Requires:	texlive-ktv-texdata
Requires:	texlive-labbook
Requires:	texlive-labelcas
Requires:	texlive-labels
Requires:	texlive-lastpage
Requires:	texlive-latex-tds
Requires:	texlive-layouts
Requires:	texlive-lazylist
Requires:	texlive-lcd
Requires:	texlive-lcg
Requires:	texlive-leading
Requires:	texlive-leaflet
Requires:	texlive-leftidx
Requires:	texlive-lengthconvert
Requires:	texlive-lettre
Requires:	texlive-lettrine
Requires:	texlive-lewis
Requires:	texlive-lhelp
Requires:	texlive-libgreek
Requires:	texlive-limap
Requires:	texlive-linegoal
Requires:	texlive-lipsum
Requires:	texlive-lisp-on-tex
Requires:	texlive-listing
Requires:	texlive-listofsymbols
Requires:	texlive-listliketab
Requires:	texlive-lkproof
Requires:	texlive-lmake
Requires:	texlive-locality
Requires:	texlive-localloc
Requires:	texlive-logbox
Requires:	texlive-logical-markup-utils
Requires:	texlive-logpap
Requires:	texlive-longfigure
Requires:	texlive-longnamefilelist
Requires:	texlive-loops
Requires:	texlive-lsc
Requires:	texlive-lstaddons
Requires:	texlive-lt3graph
Requires:	texlive-ltablex
Requires:	texlive-ltabptch
Requires:	texlive-ltxdockit
Requires:	texlive-ltxindex
Requires:	texlive-ltxkeys
Requires:	texlive-ltxnew
Requires:	texlive-ltxtools
Requires:	texlive-macroswap
Requires:	texlive-magaz
Requires:	texlive-mailing
Requires:	texlive-mailmerge
Requires:	texlive-makebarcode
Requires:	texlive-makebox
Requires:	texlive-makecell
Requires:	texlive-makecirc
Requires:	texlive-makecmds
Requires:	texlive-makedtx
Requires:	texlive-makeglos
Requires:	texlive-mandi
Requires:	texlive-manfnt
Requires:	texlive-manuscript
Requires:	texlive-marginfix
Requires:	texlive-marginnote
Requires:	texlive-mathalfa
Requires:	texlive-mathastext
Requires:	texlive-mathexam
Requires:	texlive-maybemath
Requires:	texlive-mbenotes
Requires:	texlive-mcaption
Requires:	texlive-mceinleger
Requires:	texlive-mcite
Requires:	texlive-mciteplus
Requires:	texlive-mdframed
Requires:	texlive-media9
Requires:	texlive-meetingmins
Requires:	texlive-memexsupp
Requires:	texlive-memory
Requires:	texlive-menu
Requires:	texlive-menukeys
Requires:	texlive-method
Requires:	texlive-metre
Requires:	texlive-mftinc
Requires:	texlive-midpage
Requires:	texlive-minibox
Requires:	texlive-minifp
Requires:	texlive-minipage-marginpar
Requires:	texlive-minitoc
Requires:	texlive-minorrevision
Requires:	texlive-minted
Requires:	texlive-minutes
Requires:	texlive-mla-paper
Requires:	texlive-mlist
Requires:	texlive-mmap
Requires:	texlive-mnotes
Requires:	texlive-moderncv
Requires:	texlive-moderntimeline
Requires:	texlive-modref
Requires:	texlive-modroman
Requires:	texlive-monofill
Requires:	texlive-moreenum
Requires:	texlive-morefloats
Requires:	texlive-morehype
Requires:	texlive-moresize
Requires:	texlive-moreverb
Requires:	texlive-morewrites
Requires:	texlive-movie15
Requires:	texlive-mparhack
Requires:	texlive-msc
Requires:	texlive-msg
Requires:	texlive-mslapa
Requires:	texlive-mtgreek
Requires:	texlive-multenum
Requires:	texlive-multibbl
Requires:	texlive-multicap
Requires:	texlive-multienv
Requires:	texlive-multiexpand
Requires:	texlive-multirow
Requires:	texlive-mversion
Requires:	texlive-mwe
Requires:	texlive-mweights
Requires:	texlive-mycv
Requires:	texlive-mylatexformat
Requires:	texlive-nag
Requires:	texlive-nameauth
Requires:	texlive-namespc
Requires:	texlive-ncclatex
Requires:	texlive-ncctools
Requires:	texlive-needspace
Requires:	texlive-nestquot
Requires:	texlive-newcommand
Requires:	texlive-newenviron
Requires:	texlive-newfile
Requires:	texlive-newlfm
Requires:	texlive-newspaper
Requires:	texlive-newunicodechar
Requires:	texlive-newvbtm
Requires:	texlive-newverbs
Requires:	texlive-nextpage
Requires:	texlive-nfssext-cfr
Requires:	texlive-nicefilelist
Requires:	texlive-niceframe
Requires:	texlive-nicetext
Requires:	texlive-nlctdoc
Requires:	texlive-noconflict
Requires:	texlive-noindentafter
Requires:	texlive-noitcrul
Requires:	texlive-nolbreaks
Requires:	texlive-nomencl
Requires:	texlive-nomentbl
Requires:	texlive-nonfloat
Requires:	texlive-nonumonpart
Requires:	texlive-nopageno
Requires:	texlive-notes
Requires:	texlive-notoccite
Requires:	texlive-nowidow
Requires:	texlive-nox
Requires:	texlive-ntheorem
Requires:	texlive-numberedblock
Requires:	texlive-numname
Requires:	texlive-numprint
Requires:	texlive-ocg-p
Requires:	texlive-ocgx
Requires:	texlive-ocr-latex
Requires:	texlive-octavo
Requires:	texlive-oldstyle
Requires:	texlive-onlyamsmath
Requires:	texlive-opcit
Requires:	texlive-optional
Requires:	texlive-outline
Requires:	texlive-outliner
Requires:	texlive-outlines
Requires:	texlive-overpic
Requires:	texlive-pagecolor
Requires:	texlive-pagecont
Requires:	texlive-pagenote
Requires:	texlive-pagerange
Requires:	texlive-pageslts
Requires:	texlive-paper
Requires:	texlive-papercdcase
Requires:	texlive-papermas
Requires:	texlive-papertex
Requires:	texlive-paracol
Requires:	texlive-paralist
Requires:	texlive-paresse
Requires:	texlive-parnotes
Requires:	texlive-parselines
Requires:	texlive-pas-cours
Requires:	texlive-pas-cv
Requires:	texlive-pas-tableur
Requires:	texlive-patch
Requires:	texlive-patchcmd
Requires:	texlive-pauldoc
Requires:	texlive-pawpict
Requires:	texlive-pax
Requires:	texlive-pbox
Requires:	texlive-pbsheet
Requires:	texlive-pdf14
Requires:	texlive-pdfcomment
Requires:	texlive-pdfcprot
Requires:	texlive-pdfmarginpar
Requires:	texlive-pdfscreen
Requires:	texlive-pdfslide
Requires:	texlive-pdfsync
Requires:	texlive-pdfwin
Requires:	texlive-pdfx
Requires:	texlive-pecha
Requires:	texlive-perfectcut
Requires:	texlive-perltex
Requires:	texlive-permute
Requires:	texlive-petiteannonce
Requires:	texlive-philex
Requires:	texlive-photo
Requires:	texlive-piff
Requires:	texlive-pkgloader
Requires:	texlive-placeins
Requires:	texlive-plates
Requires:	texlive-plantslabels
Requires:	texlive-plweb
Requires:	texlive-polynom
Requires:	texlive-polynomial
Requires:	texlive-polytable
Requires:	texlive-postcards
Requires:	texlive-poster-mac
Requires:	texlive-ppr-prv
Requires:	texlive-preprint
Requires:	texlive-prettyref
Requires:	texlive-preview
Requires:	texlive-printlen
Requires:	texlive-probsoln
Requires:	texlive-program
Requires:	texlive-progress
Requires:	texlive-progressbar
Requires:	texlive-properties
Requires:	texlive-prosper
Requires:	texlive-protex
Requires:	texlive-protocol
Requires:	texlive-psfragx
Requires:	texlive-pst-pdf
Requires:	texlive-pstool
Requires:	texlive-pxgreeks
Requires:	texlive-python
Requires:	texlive-qcm
Requires:	texlive-quoting
Requires:	texlive-qstest
Requires:	texlive-qsymbols
Requires:	texlive-quotchap
Requires:	texlive-quotmark
Requires:	texlive-ran_toks
Requires:	texlive-randtext
Requires:	texlive-rccol
Requires:	texlive-rcs-multi
Requires:	texlive-rcsinfo
Requires:	texlive-readarray
Requires:	texlive-realboxes
Requires:	texlive-recipe
Requires:	texlive-recipecard
Requires:	texlive-rectopma
Requires:	texlive-refcheck
Requires:	texlive-refenums
Requires:	texlive-reflectgraphics
Requires:	texlive-refman
Requires:	texlive-refstyle
Requires:	texlive-regcount
Requires:	texlive-regexpatch
Requires:	texlive-register
Requires:	texlive-regstats
Requires:	texlive-relenc
Requires:	texlive-relsize
Requires:	texlive-repeatindex
Requires:	texlive-repltext
Requires:	texlive-rjlparshap
Requires:	texlive-rlepsf
Requires:	texlive-rmpage
Requires:	texlive-robustcommand
Requires:	texlive-robustindex
Requires:	texlive-romanbar
Requires:	texlive-romanneg
Requires:	texlive-romannum
Requires:	texlive-rotfloat
Requires:	texlive-rotpages
Requires:	texlive-roundbox
Requires:	texlive-rterface
Requires:	texlive-rtkinenc
Requires:	texlive-rulercompass
Requires:	texlive-rvwrite
Requires:	texlive-sauerj
Requires:	texlive-savefnmark
Requires:	texlive-savesym
Requires:	texlive-savetrees
Requires:	texlive-scale
Requires:	texlive-scalebar
Requires:	texlive-scalerel
Requires:	texlive-scanpages
Requires:	texlive-sdrt
Requires:	texlive-secdot
Requires:	texlive-sectionbox
Requires:	texlive-sectsty
Requires:	texlive-seealso
Requires:	texlive-selectp
Requires:	texlive-semantic
Requires:	texlive-semioneside
Requires:	texlive-sepfootnotes
Requires:	texlive-seqsplit
Requires:	texlive-sf298
Requires:	texlive-sffms
Requires:	texlive-sfmath
Requires:	texlive-shadow
Requires:	texlive-shadowtext
Requires:	texlive-shadethm
Requires:	texlive-shapepar
Requires:	texlive-shipunov
Requires:	texlive-shorttoc
Requires:	texlive-show2e
Requires:	texlive-showcharinbox
Requires:	texlive-showdim
Requires:	texlive-showexpl
Requires:	texlive-showlabels
Requires:	texlive-sidecap
Requires:	texlive-sidenotes
Requires:	texlive-silence
Requires:	texlive-simplecd
Requires:	texlive-simplecv
Requires:	texlive-simplewick
Requires:	texlive-sitem
Requires:	texlive-skb
Requires:	texlive-skdoc
Requires:	texlive-skeycommand
Requires:	texlive-skeyval
Requires:	texlive-skrapport
Requires:	texlive-slantsc
Requires:	texlive-smalltableof
Requires:	texlive-smartref
Requires:	texlive-snapshot
Requires:	texlive-snotez
Requires:	texlive-soul
Requires:	texlive-spanglish
Requires:	texlive-sparklines
Requires:	texlive-sphack
Requires:	texlive-spreadtab
Requires:	texlive-spverbatim
Requires:	texlive-splitindex
Requires:	texlive-spot
Requires:	texlive-spotcolor
Requires:	texlive-srbook-mem
Requires:	texlive-srcltx
Requires:	texlive-sseq
Requires:	texlive-sslides
Requires:	texlive-stack
Requires:	texlive-stackengine
Requires:	texlive-standalone
Requires:	texlive-statistik
Requires:	texlive-stdclsdv
Requires:	texlive-stdpage
Requires:	texlive-stex
Requires:	texlive-storebox
Requires:	texlive-storecmd
Requires:	texlive-stringstrings
Requires:	texlive-sttools
Requires:	texlive-stubs
Requires:	texlive-subdepth
Requires:	texlive-subeqn
Requires:	texlive-subeqnarray
Requires:	texlive-subfigmat
Requires:	texlive-subfigure
Requires:	texlive-subfiles
Requires:	texlive-subfloat
Requires:	texlive-substitutefont
Requires:	texlive-substr
Requires:	texlive-supertabular
Requires:	texlive-svg
Requires:	texlive-svgcolor
Requires:	texlive-svn
Requires:	texlive-svn-multi
Requires:	texlive-svn-prov
Requires:	texlive-svninfo
Requires:	texlive-syntax
Requires:	texlive-syntrace
Requires:	texlive-synttree
Requires:	texlive-tabfigures
Requires:	texlive-tableaux
Requires:	texlive-tablefootnote
Requires:	texlive-tableof
Requires:	texlive-tablists
Requires:	texlive-tabls
Requires:	texlive-tabstackengine
Requires:	texlive-tabto-ltx
Requires:	texlive-tabu
Requires:	texlive-tabularborder
Requires:	texlive-tabularcalc
Requires:	texlive-tabularew
Requires:	texlive-tabulary
Requires:	texlive-tagging
Requires:	texlive-talk
Requires:	texlive-tamefloats
Requires:	texlive-tcldoc
Requires:	texlive-tcolorbox
Requires:	texlive-tdclock
Requires:	texlive-technics
Requires:	texlive-ted
Requires:	texlive-termcal
Requires:	texlive-termlist
Requires:	texlive-tex-label
Requires:	texlive-texlogos
Requires:	texlive-texmate
Requires:	texlive-texments
Requires:	texlive-texpower
Requires:	texlive-texshade
Requires:	texlive-textfit
Requires:	texlive-textgreek
Requires:	texlive-textmerg
Requires:	texlive-textpos
Requires:	texlive-theoremref
Requires:	texlive-threadcol
Requires:	texlive-threeparttable
Requires:	texlive-threeparttablex
Requires:	texlive-thinsp
Requires:	texlive-thmtools
Requires:	texlive-thumb
Requires:	texlive-thumbs
Requires:	texlive-thumby
Requires:	texlive-ticket
Requires:	texlive-titlecaps
Requires:	texlive-titlefoot
Requires:	texlive-titlepic
Requires:	texlive-titleref
Requires:	texlive-titlesec
Requires:	texlive-titling
Requires:	texlive-tocbibind
Requires:	texlive-tocloft
Requires:	texlive-tocvsec2
Requires:	texlive-todo
Requires:	texlive-todonotes
Requires:	texlive-tokenizer
Requires:	texlive-toolbox
Requires:	texlive-topfloat
Requires:	texlive-totcount
Requires:	texlive-totpages
Requires:	texlive-translations
Requires:	texlive-trfsigns
Requires:	texlive-trimspaces
Requires:	texlive-trsym
Requires:	texlive-trivfloat
Requires:	texlive-truncate
Requires:	texlive-tucv
Requires:	texlive-turnthepage
Requires:	texlive-twoinone
Requires:	texlive-twoup
Requires:	texlive-txgreeks
Requires:	texlive-type1cm
Requires:	texlive-typeface
Requires:	texlive-typogrid
Requires:	texlive-ucs
Requires:	texlive-uebungsblatt
Requires:	texlive-umoline
Requires:	texlive-underlin
Requires:	texlive-underoverlap
Requires:	texlive-undolabl
Requires:	texlive-units
Requires:	texlive-unravel
Requires:	texlive-upmethodology
Requires:	texlive-upquote
Requires:	texlive-uri
Requires:	texlive-ushort
Requires:	texlive-uwmslide
Requires:	texlive-varindex
Requires:	texlive-varsfromjobname
Requires:	texlive-varwidth
Requires:	texlive-vdmlisting
Requires:	texlive-verbasef
Requires:	texlive-verbatimbox
Requires:	texlive-verbatimcopy
Requires:	texlive-verbdef
Requires:	texlive-verbments
Requires:	texlive-version
Requires:	texlive-versions
Requires:	texlive-vertbars
Requires:	texlive-vgrid
Requires:	texlive-vhistory
Requires:	texlive-vmargin
Requires:	texlive-volumes
Requires:	texlive-vpe
Requires:	texlive-vruler
Requires:	texlive-vwcol
Requires:	texlive-wallpaper
Requires:	texlive-warning
Requires:	texlive-warpcol
Requires:	texlive-was
Requires:	texlive-widetable
Requires:	texlive-williams
Requires:	texlive-withargs
Requires:	texlive-wordlike
Requires:	texlive-wrapfig
Requires:	texlive-xargs
Requires:	texlive-xcomment
Requires:	texlive-xhfill
Requires:	texlive-xtab
Requires:	texlive-xdoc
Requires:	texlive-xfor
Requires:	texlive-xifthen
Requires:	texlive-xint
Requires:	texlive-xmpincl
Requires:	texlive-xnewcommand
Requires:	texlive-xoptarg
Requires:	texlive-xpatch
Requires:	texlive-xpeek
Requires:	texlive-xpunctuate
Requires:	texlive-xstring
Requires:	texlive-xwatermark
Requires:	texlive-xytree
Requires:	texlive-yafoot
Requires:	texlive-yagusylo
Requires:	texlive-ydoc
Requires:	texlive-yplan
Requires:	texlive-zed-csp
Requires:	texlive-ziffer
Requires:	texlive-zwgetfdate
Requires:	texlive-zwpagelayout
%rename tetex-latex
%rename texlive-texmf-latex

%description
A very large collection of add-on packages for LaTeX.

%posttrans
    %{_sbindir}/texlive.post -

#-----------------------------------------------------------------------
%files

#-----------------------------------------------------------------------
%prep
%setup -c -a0

%build

%install
